apiVersion: v2
name: product-management-web
description: A Helm chart for product-management-web
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
- name: joybox-app
  version: "0.1.0"
  repository: http://chartmuseum.joybox.local