joybox-app:
  replicaCount: 1
  appName: user

  image:
    repository: 282398598576.dkr.ecr.ap-northeast-2.amazonaws.com/user
    tag: 5660a5bcc6d4def96787d369a41d32aa43c1c433
  imagePullSecrets:
  - name: regcred

  ingress:
    enabled: true
    className: "nginx"
    hosts:
    - host: user.joybox.info
      paths:
      - path: /
        pathType: ImplementationSpecific

  livenessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 120

  readinessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 120