joybox-app:
  appName: product
  image:
    repository: 282398598576.dkr.ecr.ap-northeast-2.amazonaws.com/product
    tag: e9dc0f017715065b74c652cfeb6cca810ce08ac4
  imagePullSecrets:
  - name: regcred
  ingress:
    enabled: true
    className: "nginx"
    hosts:
    - host: product.joybox.local
      paths:
      - path: /
        pathType: ImplementationSpecific
  livenessProbe:
    failureThreshold: 5
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 20
  readinessProbe:
    failureThreshold: 5
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 20