joybox-app:
  replicaCount: 3
  appName: product
  image:
    repository: 282398598576.dkr.ecr.ap-northeast-2.amazonaws.com/product
    tag: a59e7364b610ce55e0403bc3a11f8a9568c9fb17
  imagePullSecrets:
  - name: regcred
  ingress:
    enabled: true
    className: "nginx"
    hosts:
    - host: product.joybox.local
      paths:
      - path: /
        pathType: ImplementationSpecific
  livenessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 10
  readinessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 10