joybox-app:
  replicaCount: 1
  appName: product
  image:
    repository: 282398598576.dkr.ecr.ap-northeast-2.amazonaws.com/product
    tag: e056bd8ae4f6b6769e3851dcab7aeff4f2c02f44
  imagePullSecrets:
  - name: regcred
  ingress:
    enabled: true
    className: "nginx"
    hosts:
    - host: product.joybox.info
      paths:
      - path: /
        pathType: ImplementationSpecific

  livenessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 30

  readinessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 30