joybox-app:
  appName: product
  image:
    repository: 282398598576.dkr.ecr.ap-northeast-2.amazonaws.com/product
    tag: 361eb6902fe5318c310930a790676a2fd47d4dd6
  imagePullSecrets:
  - name: regcred
  ingress:
    enabled: true
    className: "nginx"
    hosts:
    - host: product.joybox.local
      paths:
      - path: /
        pathType: ImplementationSpecific