apiVersion: v1
kind: Secret
metadata:
  name: deploy-secret
  namespace: argocd
type: Opaque
data:
  privateKey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNEek4rclpKS25td2N4cExaS0xPazVJdUQ1S2t6cEcxdmZpcFZldmtyZ1FyZ0FBQUpqK1NoTkcva29UClJnQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDRHpOK3JaSktubXdjeHBMWktMT2s1SXVENUtrenBHMXZmaXBWZXZrcmdRcmcKQUFBRUNsRnJIcGthR3JIMnFnMTZlVStEYkx2aDV4V3NOU29KRWE5WUVSUWhXdmYvTTM2dGtrcWViQnpHa3Rrb3M2VGtpNApQa3FUT2tiVzkrS2xWNitTdUJDdUFBQUFGV2RwZENCa1pYQnNiM2x0Wlc1MElITmxZM0psZEE9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K