apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-infra
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: git@github.com:appledoughnut/joybox-deployment.git
      revision: HEAD
      directories:
      - path: infra/*
  template:
    metadata:
      name: '{{path[1]}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:appledoughnut/joybox-deployment.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ path[1] }}'