apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: git@github.com:appledoughnut/joybox-deployment.git
      revision: HEAD
      directories:
      - path: apps/*
  template:
    metadata:
      name: '{{path[1]}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:appledoughnut/joybox-deployment.git
        targetRevision: HEAD
        path: '{{path}}'
        plugin:
          name: decodeSecret
          env:
            - name: RELEASE_NAME
              value: '{{path[1]}}'

      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        syncOptions:
        - CreateNamespace=true