
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: git@github.com:appledoughnut/joybox-deployment.git
      sshPrivateKeySecret:
        name: deploy-secret
        key: privateKey